create table users (
   user_cin       varchar2(50) not null primary key,
   user_name      varchar2(50) not null,
   user_last_name varchar2(50) not null,
   user_password  varchar2(255) not null,
   user_email     varchar2(50) not null,
   user_phone     varchar2(50) not null,
   user_sal       number(4)
);


create table medecins (
   med_id       varchar2(50) not null primary key,
   med_name     varchar2(50),
   med_categ    varchar2(50),
   med_price    number(4,2),
   med_quantity number(5),
   med_exp      date
);
create table prescriptions (
   pres_id      varchar2(50) not null ,
   patient_name varchar2(50),
   doctor_name  varchar2(50),
   issue_date   date,
   med_exp      date,
   status       varchar2(50),
   medications  varchar2(300),
   constraint fk_id_presc foreign key ( pres_id )
      references patients ( patient_id )
);

create table patients (
   patient_id    varchar2(50) primary key,
   patient_name  varchar2(50),
   patient_phone varchar2(50),
   patient_date  date,
   patient_note  varchar2(500)
);



create table low_stock_log (
   log_id   number
      generated by default on null as identity
   primary key,
   med_id   varchar2(50),
   med_name varchar2(100),
   quantity number,
   log_date date default sysdate
);

create table sales (
   sale_id       varchar2(50) primary key,
   med_name      varchar2(50),
   sale_quantity number,
   sale_price    number,
   sale_date     date,
   sale_categ    varchar2(50)
);


-- create sequence med_is_seq start with 1 increment by 1 nocache nocycle;
-- create sequence pres_is_seq start with 1 increment by 1 nocache nocycle;