create table low_stock_log (
   log_id   number
      generated by default on null as identity
   primary key,
   med_id   varchar2(50),
   med_name varchar2(100),
   quantity number,
   log_date date default sysdate,
   constraint fk_id_med foreign key ( med_id )
      references medications ( med_id )
);
